### ISSUE TITLE
Choose how to handle AJAX requests

### ISSUE THREAD

**Issue by f-ricci** [f-ricci/react-cooking-demo#8]

**Comment by RobertCristian** [comment]
I propose we use https://github.com/axios/axios. Is there any con in using it?

**Comment by DanCSF** [comment]
There isn't any good or bad way to do it, rather it's a matter of preference.
Axios/Fetch/Superagent have the following +'s:

- Axios -> promises
- Fetch -> it will be a standard soon
- Superagent -> callbacks

**Comment by RobertCristian** [comment]
I think this article can more or less sum up the limitations of fetch

https://medium.com/@sahilkkrazy/fetch-vs-axios-http-request-c9afa43f804e

**Comment by DanCSF** [comment]
I didn't say it's better i said it will be a standard soon.
Axios is a superior library.

**Comment by f-ricci** [comment]
axios will be then
